server:
  port: 9596

spring:
  datasource:
    username: root
    password: K512cdnk
    url: jdbc:mysql://localhost:3306/db?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # mapper 配置文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  # bean 类型文件位置
  type-aliases-package: com.cmbchina.code_generator.entity
  # 开启驼峰命名 （即 entity 中的 类变量叫 userName 对应 数据库表中的 user_name）
  configuration:
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
